FROM node:current-alpine3.22 AS builder
RUN mkdir -p /home/node/app && chown -R node:node /home/node/app
WORKDIR /home/node/app
COPY package.json .
RUN npm install
COPY . .
EXPOSE 8081
CMD ["npm", "run","dev"]

# FROM node:current-alpine3.22 AS runner
# RUN mkdir -p /home/node/app && chown -R node:node /home/node/app
# WORKDIR /home/node/app
# RUN apk update && apk upgrade
# RUN apk add --no-cache git
# COPY package.json . 
# RUN npm install --omit=dev
# COPY --from=builder /home/node/app/dist ./dist
# EXPOSE 8080
# CMD ["npm", "start"]