export const isProd = process.env.ENVIROMENT === "prod";
export const isTest = process.env.ENVIROMENT === "test";

export * from "./responseCodes";
export * from "./modelsConst";
export * from "./mailConst";

export const fileTypes: any = {
  aac: "audio/aac",
  abw: "application/x-abiword",
  arc: "application/x-freearc",
  avif: "image/avif",
  avi: "video/x-msvideo",
  azw: "application/vnd.amazon.ebook",
  bin: "application/octet-stream",
  bmp: "image/bmp",
  bz: "application/x-bzip",
  bz2: "application/x-bzip2",
  cda: "application/x-cdf",
  csh: "application/x-csh",
  css: "text/css",
  csv: "text/csv",
  doc: "application/msword",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  eot: "application/vnd.ms-fontobject",
  epub: "application/epub+zip",
  gz: "application/gzip",
  gif: "image/gif",
  htm: "text/html",
  html: "text/html",
  ico: "image/vnd.microsoft.icon",
  ics: "text/calendar",
  jar: "application/java-archive",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  js: "text/javascript",
  json: "application/json",
  jsonld: "application/ld+json",
  midi: "audio/midi, audio/x-midi",
  mid: "audio/midi, audio/x-midi",
  mjs: "text/javascript",
  mp3: "audio/mpeg",
  mp4: "video/mp4",
  mpeg: "video/mpeg",
  mpkg: "application/vnd.apple.installer+xml",
  odp: "application/vnd.oasis.opendocument.presentation",
  ods: "application/vnd.oasis.opendocument.spreadsheet",
  odt: "application/vnd.oasis.opendocument.text",
  oga: "audio/ogg",
  ogv: "video/ogg",
  ogx: "application/ogg",
  opus: "audio/opus",
  otf: "font/otf",
  png: "image/png",
  pdf: "application/pdf",
  php: "application/x-httpd-php",
  ppt: "application/vnd.ms-powerpoint",
  pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  rar: "application/vnd.rar",
  rtf: "application/rtf",
  sh: "application/x-sh",
  svg: "image/svg+xml",
  tar: "application/x-tar",
  tif: "image/tiff",
  tiff: "image/tiff",
  ts: "video/mp2t",
  ttf: "font/ttf",
  txt: "text/plain",
  vsd: "application/vnd.visio",
  wav: "audio/wav",
  weba: "audio/webm",
  webm: "video/webm",
  webp: "image/webp",
  woff: "font/woff",
  woff2: "font/woff2",
  xhtml: "application/xhtml+xml",
  xls: "application/vnd.ms-excel",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  xml: "application/xml",
  xul: "application/vnd.mozilla.xul+xml",
  zip: "application/zip",
  "3gp": "video/3gpp; audio/3gpp",
  "3g2": "video/3gpp2; audio/3gpp2",
  "7z": "application/x-7z-compressed",
};

export const nationalities = [
  { country: "Afganistán", nationality: "AFGANA", code: "AF" },
  { country: "Albania", nationality: "ALBANESA", code: "AL" },
  { country: "Alemania", nationality: "ALEMANA", code: "DE" },
  { country: "Andorra", nationality: "ANDORRANA", code: "AD" },
  { country: "Angola", nationality: "ANGOLEÑA", code: "AO" },
  { country: "Antigua y Barbuda", nationality: "ANTIGUANA", code: "AG" },
  { country: "Arabia Saudita", nationality: "SAUDÍ", code: "SA" },
  { country: "Argelia", nationality: "ARGELINA", code: "DZ" },
  { country: "Argentina", nationality: "ARGENTINA", code: "AR" },
  { country: "Armenia", nationality: "ARMENIA", code: "AM" },
  { country: "Aruba", nationality: "ARUBEÑA", code: "AW" },
  { country: "Australia", nationality: "AUSTRALIANA", code: "AU" },
  { country: "Austria", nationality: "AUSTRIACA", code: "AT" },
  { country: "Azerbaiyán", nationality: "AZERBAIYANA", code: "AZ" },
  { country: "Bahamas", nationality: "BAHAMEÑA", code: "BT" },
  { country: "Bangladés", nationality: "BANGLADESÍ", code: "BD" },
  { country: "Barbados", nationality: "BARBADENSE", code: "BB" },
  { country: "Baréin", nationality: "BAREINÍ", code: "BH" },
  { country: "Bélgica", nationality: "BELGA", code: "BE" },
  { country: "Belice", nationality: "BELICEÑA", code: "BZ" },
  { country: "Benín", nationality: "BENINÉSA", code: "BJ" },
  { country: "Bielorrusia", nationality: "BIELORRUSA", code: "BY" },
  { country: "Birmania", nationality: "BIRMANA", code: "MM" },
  { country: "Bolivia", nationality: "BOLIVIANA", code: "BO" },
  { country: "Bosnia y Herzegovina", nationality: "BOSNIA", code: "BA" },
  { country: "Botsuana", nationality: "BOTSUANA", code: "BW" },
  { country: "Brasil", nationality: "BRASILEÑA", code: "BR" },
  { country: "Brunéi", nationality: "BRUNEANA", code: "BN" },
  { country: "Bulgaria", nationality: "BÚLGARA", code: "BG" },
  { country: "Burkina Faso", nationality: "BURKINÉS", code: "BF" },
  { country: "Burundi", nationality: "BURUNDÉSA", code: "BI" },
  { country: "Bután", nationality: "BUTANÉSA", code: "BS" },
  { country: "Cabo Verde", nationality: "CABOVERDIANA", code: "CV" },
  { country: "Camboya", nationality: "CAMBOYANA", code: "KH" },
  { country: "Camerún", nationality: "CAMERUNESA", code: "CM" },
  { country: "Canadá", nationality: "CANADIENSE", code: "CA" },
  { country: "Catar", nationality: "CATARÍ", code: "QA" },
  { country: "Chad", nationality: "CHADIANA", code: "TD" },
  { country: "Chile", nationality: "CHILENA", code: "CL" },
  { country: "China", nationality: "CHINA", code: "CN" },
  { country: "Chipre", nationality: "CHIPRIOTA", code: "CY" },
  { country: "Ciudad del Vaticano", nationality: "VATICANA", code: "VA" },
  { country: "Colombia", nationality: "COLOMBIANA", code: "CO" },
  { country: "Comoras", nationality: "COMORENSE", code: "KM" },
  { country: "Corea del Norte", nationality: "NORCOREANA", code: "KP" },
  { country: "Corea del Sur", nationality: "SURCOREANA", code: "KR" },
  { country: "Costa de Marfil", nationality: "MARFILEÑA", code: "CI" },
  { country: "Costa Rica", nationality: "COSTARRICENSE", code: "CR" },
  { country: "Croacia", nationality: "CROATA", code: "HR" },
  { country: "Cuba", nationality: "CUBANA", code: "CU" },
  { country: "Dinamarca", nationality: "DANÉSA", code: "DK" },
  { country: "Dominica", nationality: "DOMINIQUÉS", code: "DM" },
  { country: "Ecuador", nationality: "ECUATORIANA", code: "EC" },
  { country: "Egipto", nationality: "EGIPCIA", code: "EG" },
  { country: "El Salvador", nationality: "SALVADOREÑA", code: "SV" },
  { country: "Emiratos Árabes Unidos", nationality: "EMIRATÍ", code: "AE" },
  { country: "Eritrea", nationality: "ERITREA", code: "ER" },
  { country: "Eslovaquia", nationality: "ESLOVACA", code: "SK" },
  { country: "Eslovenia", nationality: "ESLOVENA", code: "SI" },
  { country: "España", nationality: "ESPAÑOLA", code: "ES" },
  { country: "Estados Unidos", nationality: "ESTADOUNIDENSE", code: "US" },
  { country: "Estonia", nationality: "ESTONIA", code: "EE" },
  { country: "Etiopía", nationality: "ETÍOPE", code: "ET" },
  { country: "Filipinas", nationality: "FILIPINA", code: "PH" },
  { country: "Finlandia", nationality: "FINLANDÉSA", code: "FI" },
  { country: "Fiyi", nationality: "FIYIANA", code: "FJ" },
  { country: "Francia", nationality: "FRANCÉSA", code: "FR" },
  { country: "Gabón", nationality: "GABONÉSA", code: "GA" },
  { country: "Gambia", nationality: "GAMBIANA", code: "GM" },
  { country: "Georgia", nationality: "GEORGIANA", code: "GE" },
  { country: "Gibraltar", nationality: "GIBRALTAREÑA", code: "GI" },
  { country: "Ghana", nationality: "GHANÉSA", code: "GH" },
  { country: "Granada", nationality: "GRANADINA", code: "GD" },
  { country: "Grecia", nationality: "GRIEGA", code: "GR" },
  { country: "Groenlandia", nationality: "GROENLANDÉSA", code: "GL" },
  { country: "Guatemala", nationality: "GUATEMALTECA", code: "GT" },
  { country: "Guinea ecuatorial", nationality: "ECUATOGUINEANA", code: "GQ" },
  { country: "Guinea", nationality: "GUINEANA", code: "GN" },
  { country: "Guinea-Bisáu", nationality: "GUINEANA", code: "GW" },
  { country: "Guyana", nationality: "GUYANESA", code: "GY" },
  { country: "Haití", nationality: "HAITIANA", code: "HT" },
  { country: "Honduras", nationality: "HONDUREÑA", code: "HN" },
  { country: "Hungría", nationality: "HÚNGARA", code: "HU" },
  { country: "India", nationality: "HINDÚ", code: "IN" },
  { country: "Indonesia", nationality: "INDONESIA", code: "ID" },
  { country: "Irak", nationality: "IRAQUÍ", code: "IQ" },
  { country: "Irán", nationality: "IRANÍ", code: "IR" },
  { country: "Irlanda", nationality: "IRLANDÉSA", code: "IE" },
  { country: "Islandia", nationality: "ISLANDÉSA", code: "IS" },
  { country: "Islas Cook", nationality: "COOKIANA", code: "CK" },
  { country: "Islas Marshall", nationality: "MARSHALÉSA", code: "FK" },
  { country: "Islas Salomón", nationality: "SALOMONENSE", code: "SB" },
  { country: "Israel", nationality: "ISRAELÍ", code: "IL" },
  { country: "Italia", nationality: "ITALIANA", code: "IT" },
  { country: "Jamaica", nationality: "JAMAIQUINA", code: "JM" },
  { country: "Japón", nationality: "JAPONÉSA", code: "JP" },
  { country: "Jordania", nationality: "JORDANA", code: "JO" },
  { country: "Kazajistán", nationality: "KAZAJA", code: "KZ" },
  { country: "Kenia", nationality: "KENIATA", code: "KE" },
  { country: "Kirguistán", nationality: "KIRGUISA", code: "KG" },
  { country: "Kiribati", nationality: "KIRIBATIANA", code: "KI" },
  { country: "Kuwait", nationality: "KUWAITÍ", code: "KW" },
  { country: "Laos", nationality: "LAOSIANA", code: "LA" },
  { country: "Lesoto", nationality: "LESOTENSE", code: "LS" },
  { country: "Letonia", nationality: "LETÓNA", code: "LV" },
  { country: "Líbano", nationality: "LIBANÉSA", code: "LB" },
  { country: "Liberia", nationality: "LIBERIANA", code: "LR" },
  { country: "Libia", nationality: "LIBIA", code: "LY" },
  { country: "Liechtenstein", nationality: "LIECHTENSTEINIANA", code: "LI" },
  { country: "Lituania", nationality: "LITUANA", code: "LT" },
  { country: "Luxemburgo", nationality: "LUXEMBURGUÉSA", code: "LU" },
  { country: "Madagascar", nationality: "MALGACHE", code: "MG" },
  { country: "Malasia", nationality: "MALASIA", code: "MY" },
  { country: "Malaui", nationality: "MALAUÍ", code: "MW" },
  { country: "Maldivas", nationality: "MALDIVA", code: "MV" },
  { country: "Malí", nationality: "MALIENSE", code: "ML" },
  { country: "Malta", nationality: "MALTÉSA", code: "MT" },
  { country: "Marruecos", nationality: "MARROQUÍ", code: "MA" },
  { country: "Martinica", nationality: "MARTINIQUÉS", code: "MQ" },
  { country: "Mauricio", nationality: "MAURICIANA", code: "MU" },
  { country: "Mauritania", nationality: "MAURITANA", code: "MR" },
  { country: "México", nationality: "MEXICANA", code: "MX" },
  { country: "Micronesia", nationality: "MICRONESIA", code: "FM" },
  { country: "Moldavia", nationality: "MOLDAVA", code: "MD" },
  { country: "Mónaco", nationality: "MONEGASCA", code: "MC" },
  { country: "Mongolia", nationality: "MONGOLA", code: "MN" },
  { country: "Montenegro", nationality: "MONTENEGRINA", code: "ME" },
  { country: "Mozambique", nationality: "MOZAMBIQUEÑA", code: "MZ" },
  { country: "Namibia", nationality: "NAMIBIA", code: "NA" },
  { country: "Nauru", nationality: "NAURUANA", code: "NR" },
  { country: "Nepal", nationality: "NEPALÍ", code: "NP" },
  { country: "Nicaragua", nationality: "NICARAGÜENSE", code: "NI" },
  { country: "Níger", nationality: "NIGERINA", code: "NE" },
  { country: "Nigeria", nationality: "NIGERIANA", code: "NG" },
  { country: "Noruega", nationality: "NORUEGA", code: "NO" },
  { country: "Nueva Zelanda", nationality: "NEOZELANDÉSA", code: "NZ" },
  { country: "Omán", nationality: "OMANÍ", code: "OM" },
  { country: "Países Bajos", nationality: "NEERLANDÉSA", code: "NL" },
  { country: "Pakistán", nationality: "PAKISTANÍ", code: "PK" },
  { country: "Palaos", nationality: "PALAUANA", code: "PW" },
  { country: "Palestina", nationality: "PALESTINA", code: "PS" },
  { country: "Panamá", nationality: "PANAMEÑA", code: "PA" },
  { country: "Papúa Nueva Guinea", nationality: "PAPÚ", code: "PG" },
  { country: "Paraguay", nationality: "PARAGUAYA", code: "PY" },
  { country: "Perú", nationality: "PERUANA", code: "PE" },
  { country: "Polonia", nationality: "POLACA", code: "PL" },
  { country: "Portugal", nationality: "PORTUGUÉSA", code: "PT" },
  { country: "Puerto Rico", nationality: "PUERTORRIQUEÑA", code: "PR" },
  { country: "Reino Unido", nationality: "BRITÁNICA", code: "GB" },
  {
    country: "República Centroafricana",
    nationality: "CENTROAFRICANA",
    code: "CF",
  },
  { country: "República Checa", nationality: "CHECA", code: "CZ" },
  { country: "República de Macedonia", nationality: "MACEDONIA", code: "MK" },
  { country: "República del Congo", nationality: "CONGOLEÑA", code: "CG" },
  {
    country: "República Democrática del Congo",
    nationality: "CONGOLEÑA",
    code: "CD",
  },
  { country: "República Dominicana", nationality: "DOMINICANA", code: "DO" },
  { country: "República Sudafricana", nationality: "SUDAFRICANA", code: "ZA" },
  { country: "Ruanda", nationality: "RUANDÉSA", code: "RW" },
  { country: "Rumanía", nationality: "RUMANA", code: "RO" },
  { country: "Rusia", nationality: "RUSA", code: "RU" },
  { country: "Samoa", nationality: "SAMOANA", code: "WS" },
  {
    country: "San Cristóbal y Nieves",
    nationality: "CRISTOBALEÑA",
    code: "KN",
  },
  { country: "San Marino", nationality: "SANMARINENSE", code: "SM" },
  {
    country: "San Vicente y las Granadinas",
    nationality: "SANVICENTINA",
    code: "VC",
  },
  { country: "Santa Lucía", nationality: "SANTALUCENSE", code: "LC" },
  { country: "Santo Tomé y Príncipe", nationality: "SANTOTOMENSE", code: "ST" },
  { country: "Senegal", nationality: "SENEGALÉSA", code: "SN" },
  { country: "Serbia", nationality: "SERBIA", code: "RS" },
  { country: "Seychelles", nationality: "SEYCHELLENSE", code: "SC" },
  { country: "Sierra Leona", nationality: "SIERRALEONÉSA", code: "SL" },
  { country: "Singapur", nationality: "SINGAPURENSE", code: "SG" },
  { country: "Siria", nationality: "SIRIA", code: "SY" },
  { country: "Somalia", nationality: "SOMALÍ", code: "SO" },
  { country: "Sri Lanka", nationality: "CEILANÉSA", code: "LK" },
  { country: "Suazilandia", nationality: "SUAZI", code: "SZ" },
  { country: "Sudán del Sur", nationality: "SURSUDANÉSA", code: "SS" },
  { country: "Sudán", nationality: "SUDANÉSA", code: "SD" },
  { country: "Suecia", nationality: "SUECA", code: "SE" },
  { country: "Suiza", nationality: "SUIZA", code: "CH" },
  { country: "Surinam", nationality: "SURINAMESA", code: "SR" },
  { country: "Tailandia", nationality: "TAILANDÉSA", code: "TH" },
  { country: "Tanzania", nationality: "TANZANA", code: "TZ" },
  { country: "Tayikistán", nationality: "TAYIKA", code: "TJ" },
  { country: "Timor Oriental", nationality: "TIMORENSE", code: "TP" },
  { country: "Togo", nationality: "TOGOLÉSA", code: "TG" },
  { country: "Tonga", nationality: "TONGANA", code: "TO" },
  { country: "Trinidad y Tobago", nationality: "TRINITENSE", code: "TT" },
  { country: "Túnez", nationality: "TUNECINA", code: "TN" },
  { country: "Turkmenistán", nationality: "TURCOMANA", code: "TM" },
  { country: "Turquía", nationality: "TURCA", code: "TR" },
  { country: "Tuvalu", nationality: "TUVALUANA", code: "TV" },
  { country: "Ucrania", nationality: "UCRANIANA", code: "UA" },
  { country: "Uganda", nationality: "UGANDÉSA", code: "UG" },
  { country: "Uruguay", nationality: "URUGUAYA", code: "UY" },
  { country: "Uzbekistán", nationality: "UZBEKA", code: "UZ" },
  { country: "Vanuatu", nationality: "VANUATUENSE", code: "VU" },
  { country: "Venezuela", nationality: "VENEZOLANA", code: "VE" },
  { country: "Vietnam", nationality: "VIETNAMITA", code: "VN" },
  { country: "Yemen", nationality: "YEMENÍ", code: "YE" },
  { country: "Yibuti", nationality: "YIBUTIANA", code: "DJ" },
  { country: "Zambia", nationality: "ZAMBIANA", code: "ZM" },
  { country: "Zimbabue", nationality: "ZIMBABUENSE", code: "ZW" },
];
